SEP = " "

CLIENT_MSG_IND = 0
TARGET_MSG_IND = 1
MAX_TYPOS = 4
MAX_SCORE_PER_TASK = 100

USER_PREFIX = "[Сотрудник]"
TARGET_PREFIX = "[Верный ответ]"
CLIENT_PREFIX = "[Клиент]"
CHAT_PREFIX = "[Оценка ответа]"
SCORE_PATTERN = "Оценка: "

EMB_SCORE_BINS = [0.89, 0.91, 0.93, 0.95]
SUBSET_SIM_SCORE_BINS = [0.0, 0.25, 0.50, 0.75]
